version: "3.9"
services:
  web:
    image: ghcr.io/metastem/wikiless:latest
    environment:
      # see config.js.template for more settings
      DOMAIN: wikiless.example.org
      HTTP_ADDR: 0.0.0.0
      REDIS_URL: redis://redis
    ports:
      - 8080:8080
  redis:
    image: "redis:alpine"
